### PR TITLE
Added more complex FullCalendar configuration

### PR DESCRIPTION
**Pull request by mlewis-everley**
I have added the ability to support generic data and render that as JSON (which is passed to FullCalendar on render).

This means we can add more complex views (such as week, day), title format, etc, via configuration.

I am not 100% sure if the way I merge the default options and the customized options is the best solution (it will break if someone attempt to overwrite the function calls), but it seems to work pretty well other than that.

I am intending to up-merge this to the SS4 branch, if you are happy with pull request, I can also update the SS4 pull request.

### CODE REVIEW

**Comment by UndefinedOffset** [comment]
Is this applicable to master as is currently or after #3?

**Comment by mlewis-everley** [comment]
I ported the current master to SS4 first, then went back and added these extra features next. If you are happy to merge these changes onto master, I can go back to #3 and merge the changes in this PR into that as well.

Also, I have removed node_modules, but added a simple node script to copy the needed JS/CSS files from node_modules if someone installs npm dependencies, that way you are not required to have the barrage off node dependencies, but it should be a little easier to upgrade the dependencies if needed in the future.

**Comment by mlewis-everley** [comment]
I realised that the calendar doesn't account for a custom search in ModelAdmin, so I have also passed the current querystring as well, this will filter items sent to the calendar using `ModelAdmin::getList()`

**Comment by UndefinedOffset** [comment]
Just merged thanks :)

**Pull request merged**
